/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\BarCounterModel.glb 
Author: Gnossiennes (https://sketchfab.com/Gnossiennes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bar-counter-78c700db0d9f4d7c800fb789dfa2e057
Title: bar counter
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertStandardToBasicMaterials } from '../utils/util'

export default function BarCounterModel(props) {
  const { nodes, materials } = useGLTF('/models/BarCounterModel.glb')

  // console.log(nodes)
  // console.log(materials)
  // console.log(`[MATERIALS]: ${materials}`)

  const basicMaterials = React.useMemo(
    () => convertStandardToBasicMaterials(materials, 0.55),
    [materials]
  )

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={basicMaterials.bar_counter} />
        <mesh geometry={nodes.Object_3.geometry} material={basicMaterials.bar_counter} />
        <mesh geometry={nodes.Object_4.geometry} material={basicMaterials.bottle} />
        <mesh geometry={nodes.Object_5.geometry} material={basicMaterials.bottle} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/BarCounterModel.glb')
