/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /models/FurnitureModel.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convertStandardToBasicMaterials } from '../utils/util'

export default function FurnitureModel(props) {
  const { nodes, materials } = useGLTF('/models/FurnitureModel.glb')

  console.log(nodes)
  // console.log(materials)
  // console.log(`[MATERIALS]: ${materials}`)

  const basicMaterials = React.useMemo(
    () => convertStandardToBasicMaterials(materials, 0.55),
    [materials]
  )

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.table_top.geometry} material={basicMaterials['furniture material1']} />
      <mesh geometry={nodes.Cylinder001.geometry} material={basicMaterials['furniture material1']} />
      <mesh geometry={nodes.Cylinder001_1.geometry} material={basicMaterials['wooden part color of the furniture.001']} />
      <mesh geometry={nodes.Cylinder006.geometry} material={basicMaterials['furniture material1']} />
      <mesh geometry={nodes.Cylinder006_1.geometry} material={basicMaterials['white part of the handle of the drawer']} />
      <mesh geometry={nodes.Cylinder006_2.geometry} material={basicMaterials['wooden part color of the furniture']} />
      <mesh geometry={nodes.Cylinder003.geometry} material={basicMaterials['furniture material1']} />
      <mesh geometry={nodes.Cylinder003_1.geometry} material={basicMaterials['white part of the handle of the drawer']} />
      <mesh geometry={nodes.Cylinder003_2.geometry} material={basicMaterials['wooden part color of the furniture']} />
      <mesh geometry={nodes.Circle.geometry} material={basicMaterials['mirror material']} />
      <mesh geometry={nodes.Circle_1.geometry} material={basicMaterials['furniture material1']} />
      <mesh geometry={nodes.Circle_2.geometry} material={basicMaterials['woooden silvery part of the mirror material']} />
      <mesh geometry={nodes.Cube003.geometry} material={basicMaterials['while part of cushion material ']} />
      <mesh geometry={nodes.Cube003_1.geometry} material={basicMaterials['furniture material1']} />
    </group>
  )
}

useGLTF.preload('/models/FurnitureModel.glb')
